In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("spam.csv", encoding="latin-1")

In [3]:
df1.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [4]:
df1 = df1.loc[:, ~df1.columns.str.contains('^Unnamed')]

In [5]:
df1.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
df1 = df1.rename(columns = {"v1" : "label" , "v2" : "text"})

In [7]:
df1.head()

  label                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [8]:
df1["label"].unique()

array(['ham', 'spam'], dtype=object)

In [9]:
df1

     label                                               text
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [10]:
df1.isnull().sum()

label    0
text     0
dtype: int64

In [11]:
from datasets import load_dataset

dataset = load_dataset("ealvaradob/phishing-dataset", "combined_reduced")

c:\users\paras rana\appdata\local\programs\python\python37\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Found cached dataset phishing-dataset (C:/Users/Paras Rana/.cache/huggingface/datasets/ealvaradob___phishing-dataset/combined_reduced/1.1.0/61546d31e1df9f3fca052b0899415d0a44735b343b35333491a8b2eb718b0f63)
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.97it/s]

In [12]:
df4 = dataset['train'].to_pandas()

In [13]:
df4

                                                    text  label
0      <!doctypehtml><html lang=en xml:lang=en xmlns=...      0
1                      http://online0mgeving.ga/triodos/      1
2      metronews.ca/webapp/Login.aspx?logout=true&rur...      0
3          https://rarkuntem.co.jp.fpjiehk.cn/index1.php      1
4                            freebase.com/view/m/0ct05qn      0
...                                                  ...    ...
77672         http://www.definitions.net/definition/icon      0
77673  schedule crawler : hourahead failure start dat...      0
77674  <!doctypehtml PUBLIC "-//W3C//DTD HTML+RDFa 1....      0
77675  amazon.com/Sound-Horror-James-Philbrook/dp/B00...      0
77676  music.yahoo.com/arashi/albums/monster-single--...      0

[77677 rows x 2 columns]

In [14]:
df4["label"] = df4["label"].replace(1 , "phising")
df4["label"] = df4["label"].replace(0 , "benign")

In [15]:
df4["label"].unique()

array(['benign', 'phising'], dtype=object)

In [16]:
df4.isnull().sum()

text     0
label    0
dtype: int64

In [17]:
df4["label"].value_counts()

benign     44975
phising    32702
Name: label, dtype: int64

In [18]:
df1["label"] = df1["label"].replace("ham" , "benign")

In [19]:
df1["label"].unique()

array(['benign', 'spam'], dtype=object)

In [20]:
df = pd.concat([df1 , df4] , ignore_index=True)

In [21]:
df

        label                                               text
0      benign  Go until jurong point, crazy.. Available only ...
1      benign                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      benign  U dun say so early hor... U c already then say...
4      benign  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
83244  benign         http://www.definitions.net/definition/icon
83245  benign  schedule crawler : hourahead failure start dat...
83246  benign  <!doctypehtml PUBLIC "-//W3C//DTD HTML+RDFa 1....
83247  benign  amazon.com/Sound-Horror-James-Philbrook/dp/B00...
83248  benign  music.yahoo.com/arashi/albums/monster-single--...

[83249 rows x 2 columns]

In [22]:
df.isnull().sum()

label    0
text     0
dtype: int64

In [23]:
df["label"].value_counts()

benign     49800
phising    32702
spam         747
Name: label, dtype: int64

In [24]:
df["label"] = df["label"].replace("benign" , 0)
df["label"] = df["label"].replace("phising" , 1)
df["label"] = df["label"].replace("spam" , 2)

In [25]:
df.head()

   label                                               text
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      2  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [26]:
df

       label                                               text
0          0  Go until jurong point, crazy.. Available only ...
1          0                      Ok lar... Joking wif u oni...
2          2  Free entry in 2 a wkly comp to win FA Cup fina...
3          0  U dun say so early hor... U c already then say...
4          0  Nah I don't think he goes to usf, he lives aro...
...      ...                                                ...
83244      0         http://www.definitions.net/definition/icon
83245      0  schedule crawler : hourahead failure start dat...
83246      0  <!doctypehtml PUBLIC "-//W3C//DTD HTML+RDFa 1....
83247      0  amazon.com/Sound-Horror-James-Philbrook/dp/B00...
83248      0  music.yahoo.com/arashi/albums/monster-single--...

[83249 rows x 2 columns]

In [41]:
import nltk
from nltk.stem import PorterStemmer , WordNetLemmatizer
from nltk.corpus import stopwords
import re
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to C:\Users\Paras
[nltk_data]     Rana\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\Paras
[nltk_data]     Rana\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to C:\Users\Paras
[nltk_data]     Rana\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\Paras
[nltk_data]     Rana\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [42]:
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

In [43]:
def preprocess_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    tokens = word_tokenize(text)
    tokens = [word for word in tokens if word not in stop_words]
    tokens = [lemmatizer.lemmatize(stemmer.stem(word)) for word in tokens]
    return " ".join(tokens)

In [ ]:
df["text"] = df["text"].apply(preprocess_text)

In [27]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(df["text"] , df["label"] , test_size=0.2,stratify=df["label"],random_state=42)

In [28]:
y_train.value_counts()

0    39840
1    26161
2      598
Name: label, dtype: int64

In [29]:
y_test.value_counts()

0    9960
1    6541
2     149
Name: label, dtype: int64