In [1]:
from datasets import load_dataset

c:\users\paras rana\appdata\local\programs\python\python37\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
dataset = load_dataset("ealvaradob/phishing-dataset", "combined_reduced")

Downloading builder script: 3.27kB [00:00, ?B/s]
Downloading readme: 6.75kB [00:00, 22.7kB/s]

Downloading and preparing dataset phishing-dataset/combined_reduced to C:/Users/Paras Rana/.cache/huggingface/datasets/ealvaradob___phishing-dataset/combined_reduced/1.1.0/61546d31e1df9f3fca052b0899415d0a44735b343b35333491a8b2eb718b0f63...

Downloading data: 100%|█████████████████████████████████████████████████████████████| 521M/521M [00:37<00:00, 14.0MB/s]

Dataset phishing-dataset downloaded and prepared to C:/Users/Paras Rana/.cache/huggingface/datasets/ealvaradob___phishing-dataset/combined_reduced/1.1.0/61546d31e1df9f3fca052b0899415d0a44735b343b35333491a8b2eb718b0f63. Subsequent calls will reuse this data.

100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.32it/s]

In [6]:
df = dataset["train"].to_pandas()

In [7]:
df.head()

                                                text  label
0  <!doctypehtml><html lang=en xml:lang=en xmlns=...      0
1                  http://online0mgeving.ga/triodos/      1
2  metronews.ca/webapp/Login.aspx?logout=true&rur...      0
3      https://rarkuntem.co.jp.fpjiehk.cn/index1.php      1
4                        freebase.com/view/m/0ct05qn      0

In [8]:
df

                                                    text  label
0      <!doctypehtml><html lang=en xml:lang=en xmlns=...      0
1                      http://online0mgeving.ga/triodos/      1
2      metronews.ca/webapp/Login.aspx?logout=true&rur...      0
3          https://rarkuntem.co.jp.fpjiehk.cn/index1.php      1
4                            freebase.com/view/m/0ct05qn      0
...                                                  ...    ...
77672         http://www.definitions.net/definition/icon      0
77673  schedule crawler : hourahead failure start dat...      0
77674  <!doctypehtml PUBLIC "-//W3C//DTD HTML+RDFa 1....      0
77675  amazon.com/Sound-Horror-James-Philbrook/dp/B00...      0
77676  music.yahoo.com/arashi/albums/monster-single--...      0

[77677 rows x 2 columns]

In [9]:
df.to_csv("mixed.csv" , index=False)